// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/user/service.proto

package usersRPC

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Created              int64    `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	LastUpdated          int64    `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetOneRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneRequest) Reset()         { *m = GetOneRequest{} }
func (m *GetOneRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneRequest) ProtoMessage()    {}
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{3}
}

func (m *GetOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneRequest.Unmarshal(m, b)
}
func (m *GetOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneRequest.Marshal(b, m, deterministic)
}
func (m *GetOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneRequest.Merge(m, src)
}
func (m *GetOneRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneRequest.Size(m)
}
func (m *GetOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneRequest proto.InternalMessageInfo

func (m *GetOneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOneResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneResponse) Reset()         { *m = GetOneResponse{} }
func (m *GetOneResponse) String() string { return proto.CompactTextString(m) }
func (*GetOneResponse) ProtoMessage()    {}
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{4}
}

func (m *GetOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneResponse.Unmarshal(m, b)
}
func (m *GetOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneResponse.Marshal(b, m, deterministic)
}
func (m *GetOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneResponse.Merge(m, src)
}
func (m *GetOneResponse) XXX_Size() int {
	return xxx_messageInfo_GetOneResponse.Size(m)
}
func (m *GetOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneResponse proto.InternalMessageInfo

func (m *GetOneResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type UpdateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{6}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type PostbackLog struct {
	PostbackId           string   `protobuf:"bytes,1,opt,name=postback_id,json=postbackId,proto3" json:"postback_id,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	ResponseBody         string   `protobuf:"bytes,4,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostbackLog) Reset()         { *m = PostbackLog{} }
func (m *PostbackLog) String() string { return proto.CompactTextString(m) }
func (*PostbackLog) ProtoMessage()    {}
func (*PostbackLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{9}
}

func (m *PostbackLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostbackLog.Unmarshal(m, b)
}
func (m *PostbackLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostbackLog.Marshal(b, m, deterministic)
}
func (m *PostbackLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostbackLog.Merge(m, src)
}
func (m *PostbackLog) XXX_Size() int {
	return xxx_messageInfo_PostbackLog.Size(m)
}
func (m *PostbackLog) XXX_DiscardUnknown() {
	xxx_messageInfo_PostbackLog.DiscardUnknown(m)
}

var xxx_messageInfo_PostbackLog proto.InternalMessageInfo

func (m *PostbackLog) GetPostbackId() string {
	if m != nil {
		return m.PostbackId
	}
	return ""
}

func (m *PostbackLog) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *PostbackLog) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PostbackLog) GetResponseBody() string {
	if m != nil {
		return m.ResponseBody
	}
	return ""
}

type GetLogsRequest struct {
	PostbackId           string   `protobuf:"bytes,1,opt,name=postback_id,json=postbackId,proto3" json:"postback_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogsRequest) Reset()         { *m = GetLogsRequest{} }
func (m *GetLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogsRequest) ProtoMessage()    {}
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{10}
}

func (m *GetLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogsRequest.Unmarshal(m, b)
}
func (m *GetLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogsRequest.Merge(m, src)
}
func (m *GetLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogsRequest.Size(m)
}
func (m *GetLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogsRequest proto.InternalMessageInfo

func (m *GetLogsRequest) GetPostbackId() string {
	if m != nil {
		return m.PostbackId
	}
	return ""
}

func (m *GetLogsRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetLogsResponse struct {
	Logs                 []*PostbackLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetLogsResponse) Reset()         { *m = GetLogsResponse{} }
func (m *GetLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetLogsResponse) ProtoMessage()    {}
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e439a1d3358ac578, []int{11}
}

func (m *GetLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogsResponse.Unmarshal(m, b)
}
func (m *GetLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogsResponse.Merge(m, src)
}
func (m *GetLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetLogsResponse.Size(m)
}
func (m *GetLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogsResponse proto.InternalMessageInfo

func (m *GetLogsResponse) GetLogs() []*PostbackLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "todo.user.User")
	proto.RegisterType((*CreateRequest)(nil), "todo.user.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "todo.user.CreateResponse")
	proto.RegisterType((*GetOneRequest)(nil), "todo.user.GetOneRequest")
	proto.RegisterType((*GetOneResponse)(nil), "todo.user.GetOneResponse")
	proto.RegisterType((*UpdateRequest)(nil), "todo.user.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "todo.user.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "todo.user.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "todo.user.DeleteResponse")
	proto.RegisterType((*PostbackLog)(nil), "todo.user.PostbackLog")
	proto.RegisterType((*GetLogsRequest)(nil), "todo.user.GetLogsRequest")
	proto.RegisterType((*GetLogsResponse)(nil), "todo.user.GetLogsResponse")
}

func init() { proto.RegisterFile("rpc/user/service.proto", fileDescriptor_e439a1d3358ac578) }

var fileDescriptor_e439a1d3358ac578 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x3e, 0x9a, 0xd1, 0x9b, 0xb6, 0x9b, 0x2c, 0x34, 0xc2, 0x00, 0x51, 0xb2, 0x97, 0x6a,
	0xd2, 0x5a, 0xa9, 0x88, 0xc7, 0x3e, 0xd0, 0x22, 0x21, 0xa4, 0x09, 0xa6, 0xa0, 0x49, 0x88, 0x97,
	0x2a, 0x8d, 0xaf, 0xba, 0x88, 0x26, 0x0e, 0xb1, 0x53, 0xe8, 0x5f, 0xe0, 0x01, 0xf1, 0x13, 0xf8,
	0x9d, 0x3c, 0xa1, 0xd8, 0x49, 0x1b, 0x97, 0x69, 0x63, 0x6f, 0xf1, 0xb9, 0xf7, 0xfa, 0x1c, 0x1f,
	0x9f, 0x18, 0x8e, 0xf3, 0x2c, 0x1a, 0x15, 0x1c, 0xf3, 0x11, 0xc7, 0x7c, 0x1d, 0x47, 0x38, 0xcc,
	0x72, 0x26, 0x18, 0x69, 0x0b, 0x46, 0xd9, 0xb0, 0x2c, 0x9c, 0xbc, 0x5e, 0xc6, 0xe2, 0xba, 0x58,
	0x0c, 0x23, 0x96, 0x8c, 0x30, 0x5d, 0xb3, 0x4d, 0x96, 0xb3, 0xef, 0x9b, 0x91, 0xec, 0x8b, 0xce,
	0x97, 0x98, 0x9e, 0xaf, 0xc3, 0x55, 0x4c, 0x43, 0x81, 0xa3, 0x7f, 0x3e, 0xd4, 0x6e, 0xfe, 0x6f,
	0x03, 0xec, 0x2b, 0x8e, 0x39, 0xe9, 0x81, 0x19, 0x53, 0xcf, 0xe8, 0x1b, 0x83, 0x76, 0x60, 0xc6,
	0x94, 0x10, 0xb0, 0xd3, 0x30, 0x41, 0xcf, 0x94, 0x88, 0xfc, 0x26, 0x0f, 0xa1, 0x85, 0x49, 0x18,
	0xaf, 0x3c, 0x4b, 0x82, 0x6a, 0x41, 0x5e, 0x40, 0x27, 0xbb, 0x66, 0x29, 0xce, 0xd3, 0x22, 0x59,
	0x60, 0xee, 0xd9, 0xb2, 0xe8, 0x4a, 0xec, 0xbd, 0x84, 0x88, 0x07, 0x07, 0x51, 0x8e, 0xa1, 0x40,
	0xea, 0xb5, 0xfa, 0xc6, 0xc0, 0x0a, 0xea, 0x65, 0x39, 0xbc, 0x0a, 0xb9, 0x98, 0x17, 0x19, 0x95,
	0x65, 0x47, 0x96, 0xdd, 0x12, 0xbb, 0x52, 0x90, 0xff, 0x0d, 0xba, 0x33, 0xd9, 0x1d, 0xe0, 0xd7,
	0x02, 0xb9, 0x20, 0x4f, 0x2a, 0x69, 0x52, 0xec, 0xf4, 0xe0, 0xcf, 0xd4, 0xce, 0xcd, 0x23, 0xa3,
	0xd2, 0xf8, 0xac, 0xd6, 0x68, 0xea, 0xd5, 0x4a, 0xec, 0xd9, 0x9e, 0x58, 0x4b, 0xef, 0x6a, 0xaa,
	0xf6, 0x5f, 0x41, 0xaf, 0x26, 0xe6, 0x19, 0x4b, 0x39, 0x92, 0x53, 0xb0, 0x4b, 0xe3, 0x25, 0xb3,
	0x3b, 0x3e, 0x1c, 0x6e, 0xaf, 0x62, 0x58, 0x7a, 0x18, 0xc8, 0xa2, 0x3f, 0x80, 0xee, 0x5b, 0x14,
	0x1f, 0xd2, 0xad, 0xde, 0x47, 0x3b, 0x6b, 0x77, 0x4c, 0x66, 0x4c, 0x4b, 0x82, 0xba, 0xf3, 0x3e,
	0x04, 0xbf, 0x0c, 0xe8, 0x2a, 0x73, 0xee, 0x62, 0xd8, 0x5a, 0x65, 0xde, 0x6a, 0x95, 0xf5, 0x5f,
	0x56, 0xd9, 0xb7, 0x5b, 0x55, 0x2b, 0xba, 0xa7, 0x55, 0x6f, 0x70, 0x85, 0x77, 0x1f, 0xc4, 0x3f,
	0x82, 0x5e, 0xdd, 0xa9, 0x08, 0xfc, 0x9f, 0x06, 0xb8, 0x97, 0x8c, 0x8b, 0x45, 0x18, 0x7d, 0xb9,
	0x60, 0x4b, 0xf2, 0x1c, 0xdc, 0xac, 0x5a, 0xce, 0xb7, 0x49, 0x86, 0x1a, 0x7a, 0x47, 0xcb, 0x06,
	0x2e, 0x42, 0x51, 0xf0, 0x79, 0xc4, 0xa8, 0xb2, 0xa4, 0x15, 0x80, 0x82, 0x66, 0x8c, 0x62, 0x33,
	0xa5, 0x96, 0x9e, 0xd2, 0x53, 0xe8, 0xe6, 0x15, 0xef, 0x7c, 0xc1, 0xe8, 0xa6, 0xca, 0x78, 0xa7,
	0x06, 0xa7, 0x8c, 0x6e, 0xfc, 0x4f, 0xf2, 0x36, 0x2f, 0xd8, 0x92, 0xd7, 0xa7, 0x19, 0xdc, 0x20,
	0x69, 0x77, 0xac, 0xa6, 0xb6, 0xa7, 0xd0, 0x16, 0x71, 0x82, 0x5c, 0x84, 0x49, 0x26, 0x95, 0x59,
	0xc1, 0x0e, 0xf0, 0x27, 0x70, 0xb8, 0xdd, 0xb9, 0xb2, 0xf7, 0x0c, 0xec, 0x15, 0x5b, 0x72, 0xcf,
	0xe8, 0x5b, 0x03, 0x77, 0x7c, 0xdc, 0xb0, 0xb7, 0xe1, 0x49, 0x20, 0x7b, 0xc6, 0x3f, 0x4c, 0xe8,
	0x94, 0xa6, 0xf3, 0x8f, 0xea, 0x21, 0x21, 0x13, 0x70, 0x54, 0xb0, 0x89, 0xd7, 0x18, 0xd4, 0x7e,
	0xb2, 0x93, 0xc7, 0x37, 0x54, 0x2a, 0xee, 0x09, 0x38, 0x2a, 0xb6, 0xda, 0xb8, 0x96, 0x79, 0x6d,
	0x7c, 0x2f, 0xe3, 0x13, 0x70, 0x54, 0x56, 0xb4, 0x71, 0x2d, 0xd0, 0xda, 0xf8, 0x5e, 0xb0, 0x26,
	0xe0, 0xa8, 0x24, 0x68, 0xe3, 0x5a, 0x8c, 0xb4, 0x71, 0x3d, 0x36, 0x53, 0xf8, 0xfc, 0xa0, 0x84,
	0x79, 0x70, 0x39, 0x5b, 0x38, 0xf2, 0x0d, 0x7c, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x29,
	0xeb, 0xb0, 0x6b, 0x05, 0x00, 0x00,
}
